### ISSUE TITLE
java.lang.Exception: org/apache/http/util/mime_type.list resource not found

### ISSUE THREAD

**Issue by coolsnow77** [sidooo/ucloud-sdk-java#1]
您好, 报告mime_type.list 错误， 怎么解决下？

**Comment by coolsnow77** [comment]
我添加的maven 依赖是		
<dependency>
			<groupId>com.sidooo</groupId>
			<artifactId>ucloud-java-sdk-ufile</artifactId>
			<version>1.0</version>
		</dependency>， 是不是包里面的org/apache/http/util/mime_type.list 没打包进去，还是路径错了?

**Comment by coolsnow77** [comment]
org/apache/http/util/mime_type.list.  		<dependency>
			<groupId>com.sidooo</groupId>
			<artifactId>ucloud-java-sdk-ufile</artifactId>
			<version>1.0</version>
		</dependency>

**Comment by analyst004** [comment]
你是用的Maven中央库的1.0版本jar吧

**Comment by analyst004** [comment]
UFileRequest已经不使用了， UFileRequest是UCloud官方的，新的是URequest

**Comment by analyst004** [comment]
我马上Relese一下1.1到Maven中央库

**Comment by coolsnow77** [comment]
好的, 我使用URequest 测试下. 先谢谢了。

**Comment by coolsnow77** [comment]
那我等下你的1.1 版本, 发布后@我 下， 谢谢了.

**Comment by analyst004** [comment]
@coolsnow77  已经发布， 中央库同步需要点时间， 一般2小时内。
另外，使用方法可以参考test方法下的用例，对外接口的是UFile对象 

        credentials = new UFileCredentials();
        credentials.loadConfig(UFILE_CONFIG_FILE);
        ufile = UFileClientBuilder.standard(credentials, Region.CN_BJ2);

**Comment by analyst004** [comment]
mime_type.list是从UCloud官方SDK带过来的。 
v1.2中已经彻底删除所有废弃的UCloud的官方代码， 包括mime_type.list
