### ISSUE TITLE
getParent() 在取父路径时error

### ISSUE THREAD

**Issue by lyu00001** [sidooo/ucloud-sdk-java#10]
UObjectSummary objectSummary = new UObjectSummary();
String fileName = entry.getAsJsonObject().get("FileName").getAsString();
String prefix = Paths.get(fileName).getParent().toString();

当fileName 是test.xmind这种时取父路径会出现异常导致程序挂掉。
getParent() 在取路径时error

**Comment by analyst004** [comment]
问题已确认。
当调用listObjects， prefix设置为"", 枚举bucket的根目录下的Object会导致该问题。
问题已在1.4.6中得到修正。同时增加了2个单元测试用例。

    @Test(expected = Test.None.class)
    public void test13() throws Exception
    {
        File testFile = new File(LOCAL_TEST_FILE);
        if (!ufile.doesObjectExist(TEST_BUCKET, TEST_KEY)) {
            ufile.putObject(TEST_BUCKET, TEST_KEY, testFile);
        }

        UObjectListing objectListing = ufile.listObjects(TEST_BUCKET, "");
        assertEquals(0, objectListing.getCommonPrefixes().size());

        ufile.deleteObject(TEST_BUCKET, TEST_KEY);
    }

    @Test(expected = Test.None.class)
    public void test14() throws Exception
    {
        UObjectListing objectListing = ufile.listObjects(TEST_BUCKET, "");
        assertEquals(0, objectListing.getCommonPrefixes().size());
        assertEquals(0, objectListing.getObjectSummaries().size());
    }

**Comment by analyst004** [comment]
非常感谢您的反馈
