### ISSUE TITLE
listobject 当type类型时未知的时候，ucloud的json可能不会返回该类型

### ISSUE THREAD

**Issue by lyu00001** [sidooo/ucloud-sdk-java#11]
![wechatimg107](https://user-images.githubusercontent.com/36392513/42496512-ea1ddfa6-8458-11e8-8a39-f92c9e69f50c.jpeg)
当类型是未定义的时候，listobject返回的json串不会有该类型。导致程序报错

**Comment by analyst004** [comment]
该问题已经确认存在。 会导致listObjects抛出NPE。
该问题已经得到修正并在1.4.7中release。 
非常感谢您的反馈
