### ISSUE TITLE
我在您的mimetype 文件中，没有找到以下类型, 请新增一下mime 类型, 谢谢.

### ISSUE THREAD

**Issue by coolsnow77** [sidooo/ucloud-sdk-java#4]
.docx   application/vnd.openxmlformats-officedocument.wordprocessingml.document
.xlsx    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
.pptx    application/vnd.openxmlformats-officedocument.presentationml.presentation

**Comment by analyst004** [comment]
已添加，并通过单元测试， 请更新
