### ISSUE TITLE
UFileClient putObject

### ISSUE THREAD

**Issue by lyu00001** [sidooo/ucloud-sdk-java#5]
public UObjectMetadata putObject(String bucketName, String objectKey, InputStream objectStream, String contentType) 
类里面check状态函数。Mimetypes.getInstance().existMimeType(contentType)本身应该是check当前类型是否存在如果存在返回true或false。但是我返回true后又“!” 变false了。在下面checkstat的判断的时候就变成无效contentType。
 Preconditions.checkState(!Mimetypes.getInstance().existMimeType(contentType), "contentType is illegal");

@analyst004 @coolsnow77 问下这个用的有问题还是？？

**Comment by analyst004** [comment]
我check一下

**Comment by analyst004** [comment]
请问您是用的哪个版本的jar， 我测试了最新的1.4.1， 暂时未发现所描述的问题，不知道是否我未完全理解您的问题描述，我的测试代码如下

        mimetype = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
        assertEquals(mimetype, Mimetypes.getInstance().getMimetype("test.pptx"));
        
        // 第一次调用
        assertTrue(Mimetypes.getInstance().existMimeType(mimetype));

        //连续两次调用existMimeType
        assertTrue(Mimetypes.getInstance().existMimeType(mimetype));
        
        // 取反
        assertFalse(!Mimetypes.getInstance().existMimeType(mimetype));

**Comment by analyst004** [comment]
我明白了， 已确认问题

**Comment by lyu00001** [comment]
Mimetypes.getInstance().existMimeType(contentType) 这个函数本身是做什么用的。比如我输入一个已知的类型，application/octet-stream。比如我输入这个类型。然后我应该得到true的吧。但是check的时候取反出错了。不知道用的有问题还是？？

**Comment by analyst004** [comment]
该函数是用于检查用户输入的Content Type是否是合法的mime，如果输入的是application/octet-stream。existMimeType是返回true。
您的问题已经得到修正， 我已经release了1.4.2， 由于maven中央库的同步会稍慢， 在几个小时后， 您就可以在中央库中得到最新的jar了。

**Comment by analyst004** [comment]
该问题是我在putObject函数中， 使用checkState不当导致
正确的代码应该是
        checkState(Mimetypes.getInstance().existMimeType(contentType), "contentType is illegal");
而我犯了一个错误
        checkState(!Mimetypes.getInstance().existMimeType(contentType), "contentType is illegal");

**Comment by analyst004** [comment]
非常抱歉给您带来了麻烦， 再次感谢您的使用
