### ISSUE TITLE
UFileClient listObjects

### ISSUE THREAD

**Issue by lyu00001** [sidooo/ucloud-sdk-java#6]
ListObjectRequest.class 这个文件里。

在bucket有个object size 是0。然后为list这个文件，返回的requset body字段里没有size这个字段。程序就挂。是ucloud对于object 大小是0 的是不返回size字段吗？？？
74行。
Long size = entry.getAsJsonObject().get("Size").getAsLong();

@analyst004 @coolsnow77

**Comment by analyst004** [comment]
我确认一下

**Comment by lyu00001** [comment]
是真没有。size这个字段。不用确认了。object大小为0真没给返回size这个大小.

**Comment by analyst004** [comment]
的确如您所描述， 我修正一下该问题

**Comment by analyst004** [comment]
该问题在1.4.3中已修复， 并增加了单元测试用例。
1.4.3已经Release。
再次感谢您的Bug报告
