### ISSUE TITLE
listobject的时候缺参数

### ISSUE THREAD

**Issue by lyu00001** [sidooo/ucloud-sdk-java#7]
正常listobject应该是可以限定参数。
GET /?list&prefix=<prefix>&marker=<marker>&limit=<limit>
Host: <bucket_name>.ufile.ucloud.cn
Authorization: <token> 
代码里：
ListObjectRequest.class 28行
好像只是限定了limit 并没有限定prefix

 public ListObjectRequest(UFileRegion region, String bucketName, String prefix, int limit) {
        super(HttpType.GET, region, bucketName);
        this.limit = 20;
        this.prefix = prefix;
        this.limit = limit;
        this.addParameter("limit", Integer.toString(limit));
    }

@analyst004 @coolsnow77

**Comment by analyst004** [comment]
感谢您的Bug报告， 问题已经确认并在Release 1.4.4中得到修复。同时增加了单元测试用例。
1.4.4 版本已于刚才发布。

**Comment by analyst004** [comment]
测试用例如下：
        File testFile = new File(LOCAL_TEST_FILE);
        if (!ufile.doesObjectExist(TEST_BUCKET, String.format("a/b/c/%s", TEST_KEY))) {
            ufile.putObject(TEST_BUCKET, String.format("a/b/c/%s", TEST_KEY), testFile);
        }
        if (!ufile.doesObjectExist(TEST_BUCKET, String.format("a/b/%s", TEST_KEY))) {
            ufile.putObject(TEST_BUCKET, String.format("a/b/%s", TEST_KEY), testFile);
        }
        if (!ufile.doesObjectExist(TEST_BUCKET, String.format("a/%s", TEST_KEY))) {
            ufile.putObject(TEST_BUCKET, String.format("a/%s", TEST_KEY), testFile);
        }

        UObjectListing objectListing = ufile.listObjects(TEST_BUCKET, "a", 10);
        assertEquals(objectListing.getObjectSummaries().size(), 3);
        assertEquals(objectListing.getObjectSummaries().get(0).getObjectKey(), String.format("a/b/c/%s", TEST_KEY));
        assertEquals(objectListing.getObjectSummaries().get(1).getObjectKey(), String.format("a/b/%s", TEST_KEY));
        assertEquals(objectListing.getObjectSummaries().get(2).getObjectKey(), String.format("a/%s", TEST_KEY));

        objectListing = ufile.listObjects(TEST_BUCKET, "a/b", 10);
        assertEquals(objectListing.getObjectSummaries().size(), 2);
        assertEquals(objectListing.getObjectSummaries().get(0).getObjectKey(), String.format("a/b/c/%s", TEST_KEY));
        assertEquals(objectListing.getObjectSummaries().get(1).getObjectKey(), String.format("a/b/%s", TEST_KEY));

        objectListing = ufile.listObjects(TEST_BUCKET, "a/b/c", 10);
        assertEquals(objectListing.getObjectSummaries().size(), 1);
        assertEquals(objectListing.getObjectSummaries().get(0).getObjectKey(), String.format("a/b/c/%s", TEST_KEY));

        ufile.deleteObject(TEST_BUCKET, String.format("a/b/c/%s", TEST_KEY));
        ufile.deleteObject(TEST_BUCKET, String.format("a/b/%s", TEST_KEY));
        ufile.deleteObject(TEST_BUCKET, String.format("a/%s", TEST_KEY));

**Comment by lyu00001** [comment]
好的，谢谢辛苦了！！

**Comment by analyst004** [comment]
@lyu00001  这是我应该做的， 倒是应该感谢您提了这么多bug， 希望您使用顺利。

**Comment by lyu00001** [comment]
哦好的，那我再看看代码争取再提两个😊，maven的话多久能同步上去？？

**Comment by analyst004** [comment]
时间不定， 一般2-8个小时

**Comment by analyst004** [comment]
您尽管提bug， 该项目以后可能会成为UCloud的官方Java SDK，你的付出不会浪费😄

**Comment by lyu00001** [comment]
刚才是开玩笑，顺便问一下这个sdk会做copy/move 这种功能吗？？把一个object移动到另一个地方？？

**Comment by lyu00001** [comment]
因为原生态到ucloud没有相关到api去move/copy。所以问下这个sdk以后会做相应功能吗？

**Comment by analyst004** [comment]
由于UFIle团队的Http API中未提供move/copy的相关操作， 所以我在SDK中暂时无法提供该函数

**Comment by lyu00001** [comment]
了解

**Comment by analyst004** [comment]
我会和UFile团队沟通这个问题， 后续会通知您结果

**Comment by analyst004** [comment]
@lyu00001  经过和UFile团队的沟通， 他们明确表示不会现在在API中增加copy接口。 但他们准备在9月的时候对UFile进行一次大的改版， 届时也会重构API， 届时会增加copy接口。

**Comment by lyu00001** [comment]
了解

在 2018-06-27 10:52:49，"张晓康" <notifications@github.com> 写道：


@lyu00001 经过和UFile团队的沟通， 他们明确表示不会现在在API中增加copy接口。 但他们准备在9月的时候对UFile进行一次大的改版， 届时也会重构API， 届时会增加copy接口。
