### ISSUE TITLE
API接口getObjectMetadata问题

### ISSUE THREAD

**Issue by lyu00001** [sidooo/ucloud-sdk-java#8]
getObjectMetadata 这个本身属于headobject的吧。如果我没有这个相关文件，可能会报错404not found但是你这个接口应该返回空null吧。你直接抛异常我这全挂了。。。。我觉得你可以打错误log但是不能让它挂啊。。。
@analyst004 @coolsnow77

**Comment by analyst004** [comment]
该问题是这样的， 按照工程规范， 一切RuntimeException， 原则上都是都用check来做预检查。
也就是说这样的场景下， 处理方式是这样
if (doesObjectExist(xxx)){
    getObjectMetadata(xxx);
}

**Comment by lyu00001** [comment]
是。但是我觉得你这个问题也是需要改的。一是没有例子我也不知道怎么用的，再者我误用的话直接挂这个也不太合理吧。

**Comment by lyu00001** [comment]
我感觉还是最好要有范例的。。。最主要是真不知道怎么用。

**Comment by analyst004** [comment]
我赞同您关于增加使用说明的建议，会在文档中进行补充。 
 但在sdk中直接返回null， 确实是弊大于利，相当于直接把错误给吞掉了， 如果按照这个逻辑， 那么java也不需要设置RuntimeException了。

**Comment by analyst004** [comment]
您所提到的getObjectMetadata中LastModified时间不正确的问题已确认， 并在1.4.5版本中得到修正。
谢谢反馈。
