### ISSUE TITLE
listObjects返回值问题

### ISSUE THREAD

**Issue by lyu00001** [sidooo/ucloud-sdk-java#9]
UObjectListing listObjects(String bucketName, String prefix, Integer limit)
这个接口如果我没list到内容。你这个貌似没有返回null值啊。我这没法判断到底list成功没。。。
@coolsnow77 @analyst004 

ps：要不大哥咱们加个微信。

**Comment by analyst004** [comment]
可以的， 微信加我analyst004

**Comment by analyst004** [comment]
您提到的UObjectListing中getCommonPrefixs方法返回为空的问题已确认， 并在1.4.5中得到修正。
谢谢反馈。
